export const HEALTH_FACILITY_LEVELS = ["C", "D", "H"]
export const HEALTH_FACILITY_LEGAL_FORMS = ["C", "D", "G", "P"]
export const HEALTH_FACILITY_SUB_LEVELS = ["I", "N", "R"]

export const RIGHT_LOCATION_ADD = 121902;
export const RIGHT_LOCATION_EDIT = 121903;
export const RIGHT_LOCATION_DELETE = 121904;
export const RIGHT_LOCATION_MOVE = 121905;

export const RIGHT_HEALTH_FACILITY_ADD = 121102;
export const RIGHT_HEALTH_FACILITY_EDIT = 121103;
export const RIGHT_HEALTH_FACILITY_DELETE = 121104;
